Feature. Make simple Libarary
elfin-git/Awesome-Books pull request #1
Opened 2022-08-01 20:28 UTC by elfin-git

- We first set up the project using medium-fidelity wireframe in html.
- We then made a function to add books in javascript.
- We then proceeded to make a function that removes books.
- After that we made a function that stores all the books data in the local storage.
- Lastly we debugged checked for linter errors.

2022-08-02 07:41 UTC, muneebulrehman requested changes
Hi @elfin-git @kidde60 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- Consider resetting the values inside the input fields. It makes it difficult to add a new book since the user has to clear the input fields from the previous data.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-02 07:41 UTC, muneebulrehman commented on index.js
> +const getDataFromStorage = () => {
After adding a few books, followed by reloading the page, the books from the local storage are not populated on the page. Consider fixing it.

2022-08-02 07:41 UTC, muneebulrehman commented on index.js
> +const removeBooks = () => {
The remove functionality doesn't work. It deletes the book from the UI but doesn't delete it from the local storage. Consider fixing it.

2022-08-03 08:23 UTC, mikethreels approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 19:18 UTC, merged